version: '3.9'

services:

  drupal:
    image: drupal:9
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    secrets:
      - drumpal_db_password
      - drumpal_db_name
      - drumpal_db_user
    environment:
      - DRUPAL_DB_HOST=postgres
      - DRUPAL_DB_PORT=5432
      - DRUPAL_DB_USER_FILE=/run/secrets/drumpal_db_user
      - DRUPAL_DB_PASSWORD_FILE=/run/secrets/drumpal_db_password
      - DRUPAL_DB_NAME_FILE=/run/secrets/drumpal_db_name

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER_FILE=/run/secrets/drumpal_db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/drumpal_db_password
      - POSTGRES_DB_FILE=/run/secrets/drumpal_db_name
    volumes:
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - drumpal_db_password
      - drumpal_db_name
      - drumpal_db_user

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  drumpal_db_password:
    external: true
  drumpal_db_name:
    external: true
  drumpal_db_user:
    external: true
